# Generated by Django 5.2.7 on 2025-10-12 16:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Hora')),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Minuto')),
                ('second', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='Segundo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('repeat_daily', models.BooleanField(default=False, verbose_name='Repetir Diariamente')),
                ('repeat_weekdays', models.JSONField(blank=True, default=list, verbose_name='Días de Repetición')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('sound_type', models.CharField(choices=[('beep', 'Pitido Simple'), ('chime', 'Campanilla'), ('bell', 'Campana'), ('tone', 'Tono'), ('custom', 'Personalizado')], default='beep', max_length=10, verbose_name='Tipo de Sonido')),
                ('volume', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Volumen')),
                ('snooze_enabled', models.BooleanField(default=True, verbose_name='Snooze Habilitado')),
                ('snooze_duration', models.IntegerField(default=5, verbose_name='Duración Snooze (minutos)')),
                ('max_snooze_count', models.IntegerField(default=3, verbose_name='Máximo Snoozes')),
                ('times_triggered', models.IntegerField(default=0, verbose_name='Veces Disparada')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Última Vez Disparada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
                'ordering': ['hour', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='CircularListState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('hours_24', 'Horas 24h'), ('hours_12', 'Horas 12h'), ('minutes', 'Minutos'), ('seconds', 'Segundos'), ('days', 'Días')], max_length=10, unique=True, verbose_name='Tipo de Lista')),
                ('current_value', models.IntegerField(verbose_name='Valor Actual')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Estado de Lista Circular',
                'verbose_name_plural': 'Estados de Listas Circulares',
            },
        ),
        migrations.CreateModel(
            name='ClockConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración Principal', max_length=100, verbose_name='Nombre')),
                ('time_format', models.CharField(choices=[('12h', '12 Horas (AM/PM)'), ('24h', '24 Horas')], default='12h', max_length=3, verbose_name='Formato de Hora')),
                ('theme', models.CharField(choices=[('dark', 'Tema Oscuro'), ('light', 'Tema Claro'), ('blue', 'Tema Azul'), ('green', 'Tema Verde')], default='dark', max_length=10, verbose_name='Tema')),
                ('show_seconds', models.BooleanField(default=True, verbose_name='Mostrar Segundos')),
                ('show_analog_clock', models.BooleanField(default=True, verbose_name='Mostrar Reloj Analógico')),
                ('show_digital_clock', models.BooleanField(default=True, verbose_name='Mostrar Reloj Digital')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='Sincronización Automática')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Configuración del Reloj',
                'verbose_name_plural': 'Configuraciones del Reloj',
            },
        ),
        migrations.CreateModel(
            name='ClockStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_runtime_minutes', models.IntegerField(default=0, verbose_name='Tiempo Total Ejecutándose (minutos)')),
                ('alarms_triggered', models.IntegerField(default=0, verbose_name='Alarmas Disparadas')),
                ('format_changes', models.IntegerField(default=0, verbose_name='Cambios de Formato')),
                ('sync_operations', models.IntegerField(default=0, verbose_name='Sincronizaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Estadística del Reloj',
                'verbose_name_plural': 'Estadísticas del Reloj',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('triggered', 'Disparada'), ('snoozed', 'Pospuesta'), ('dismissed', 'Descartada'), ('missed', 'Perdida')], max_length=10, verbose_name='Estado')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Disparada En')),
                ('user_action', models.CharField(blank=True, max_length=100, verbose_name='Acción del Usuario')),
                ('response_time', models.DurationField(blank=True, null=True, verbose_name='Tiempo de Respuesta')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='clock.alarm', verbose_name='Alarma')),
            ],
            options={
                'verbose_name': 'Registro de Alarma',
                'verbose_name_plural': 'Registros de Alarmas',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
