# Generated by Django 5.2.7 on 2025-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_alarm_day_of_week_alarm_period_alter_alarm_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='alarm_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Calendario'),
        ),
    ]
