# Generated by Django 5.2.7 on 2025-10-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_alarm_alarm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockconfiguration',
            name='timezone',
            field=models.CharField(default='America/Bogota', max_length=64, verbose_name='Zona Horaria'),
        ),
    ]
