# Generated by Django 5.2.7 on 2025-10-12 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0004_clockconfiguration_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockconfiguration',
            name='timezone',
        ),
        migrations.AddField(
            model_name='alarm',
            name='silenced_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silenciada Hasta'),
        ),
        migrations.AddField(
            model_name='alarmlog',
            name='alarm_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título de la Alarma'),
        ),
        migrations.AlterField(
            model_name='alarmlog',
            name='alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='clock.alarm', verbose_name='Alarma'),
        ),
    ]
